---
title: "YUEP"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
---

# 山口大学教育心理・読書会

YUEP読書会は，心理学を学ぶ上でより広い視野，観点から対象を捉えることができるように，心理学だけでなく哲学，認知科学，コンピュータ科学，統計学，社会学などの書籍を隔月で選定し，読むことにしています。興味がある方はどなたでもご参加いただけます。

## 次回予告 

次回は2020.06.05　課題図書は「責任という虚構」(小坂井敏晶)です。

## 活動記録

1.  2012.12.08 YUEP pre.「ミンスキー博士の脳の探検」(於山口大学)
2.  2013.01.12 YUEP \#1. 「ユーザーイリュージョン」(於山口大学)
3.  2013.03.16 YUEP \#2. 「神々の沈黙」(於山口大学)
4.  2013.04.28 YUEP \#3.「ヴィトゲンシュタイン論理哲学論考を読む」(於山口大学)
5.  2013.05.29 YUEP \#4. 「連続性の哲学」(於山口大学)
6.  2013.06.21 YUEP \#5. 「複雑系」(於山口大学)
7.  2013.07.26 YUEP \#6. 「解明される意識」(於山口大学)
8.  2013.08.26 YUEP \#7. 「生態学的視覚論」(於山口大学)
9.  2013.09.15 YUEP \#8. 「心の仕組み（前）」(於山口大学)
10. 2013.10.26 YUEP \#9. 「心の仕組み（後）」(於山口大学)
11. 2013.11.24 YUEP \#10.「科学の終焉」(於山口大学)
12. 2013.12.01-02 YUEP \#11.「オートポイエーシス」(八女合宿)
13. 2014.02.02　YUEP \#12 「エクリチュールと差異」(於山口大学)
14. 2014.03.21 YUEP \#13.「皇帝の新しい心」(於山口大学)
15. 2014.05.18 YUEP \#14.「科学の解釈学」(於山口大学)
16. 2014.08.20 YUEP \#15. 「名前になんの意味があるのか」(於山口大学)
17. 2014.10.12 YUEP \#16. 「社会心理学講義」(於山口大学)
18. 2014.12.06 YUEP \#17. 「偶然の科学」(於関西大学)
19. 2015.01.31 YUEP \#18. 「理不尽な進化」(於関西大学)
20. 2015.05.24 YUEP \#19.　「意識の神秘」(於広島大学)
21. 2015.06.20 YUEP \#20.　「科学的実在論を擁護する」(於広島大学)
22. 2015.08.16-17 YUEP \#21. 「フーリエの冒険」(雲仙合宿)
23. 2015.11.29 YUEP \#22. 「それは私がしたことなのか」(於広島大学)
24. 2016.02.13 YUEP \#23. 「ニクラス・ルーマン入門」(於関西大学)
25. 2016.05.15 YUEP \#24.　「いきものとなまものの哲学」(於関西大学)
26. 2016.07.29 YUEP \#25.「意識と脳――思考はいかにコード化されるか」(於山口大学)
27. 2016.11.05 YUEP \#26.「心理学を真面目に考える方法」『心理学評論』第59巻1号合わせ読み(於山口大学)
28. 2017.02.18 YUEP \#27. 「生物学の哲学入門」(於山口大学)
29. 2018.10.14 YUEP \#28. 「進化の謎を数学で解く」(於広島大学)
30. 2019.02.17 YUEP \#29.「予測不可能性，あるいは計算の魔」(於山口大学)
31. 2019.08.31 YUEP \#30. 「進化の意外な順序」(於千里中央)
32. 2019.12.14 YUEP \#31. 「表現と介入」(於千里中央)
33. 2019.06.05 YUEP \#32.　「責任という虚構」(オンライン開催)