baseurl = "https://example.com/"
title = "Kosugitti Labo ver.10"
theme = "kosugitti"
languageCode = "jp"
copyright = "My Name"
disqusShortname = "XXX"
googleAnalytics = "XXX"
publishDir = "docs"
hasCJKLanguage = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
    name = "My Name"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Kosugitti Labo"
    description = "こすけん"
    github = "https://github.com/kosugitti"
    linkedin = "https://linkedin.com/in/kosugitti/"
    twitter = "https://twitter.com/kosugitti"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Sun, Apr 1, 2018"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
