## Basic Configuration
baseurl = "https://kosugitti.github.io/kosugitti10/"
languageCode = "jp"
publishDir = "docs"
hasCJKLanguage = true
theme = "hyde-hyde"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Kosugitti"
    title = "Kosugitti Labo 10"
    # description = "..."
    authorimage = "/img/hugo.png"
    dateformat = "April 3, 2018"
    highlightjs = true
    # highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "kosugitti"
    instagram = "kosugitti"
    linkedin = "kosugitti"
    twitter = "kosugitti"
    facebook = "Koji Kosugi"
    email = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
