baseurl = "https://kosugitti.github.io/kosugitti10"
title = "Kosugitti Labo ver.10"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"
# Comment the themesDir option if you use this theme in production
relativeurls = true
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "小杉考司"
    bio = "専修大学人間科学部"
    location = "神奈川県"
    site_description = "小杉考司のオンライン研究"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "css/images/avatar2.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = "kosugitti@gmail.com"
    logo = "css/images/logo2.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "About"
    link   = "about/"

[[params.menu]]
    before = false
    label  = "Works"
    link   = "works/"

[[params.menu]]
    before = false
    label  = "Notes"
    link   = "notes/"

[[params.menu]]
    before = false
    label  = "Support"
    link   = "support/"

[[params.menu]]
    before = false
    label  = "YUEP"
    link   = "yuep/"


# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/kosugitti"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "kosugitti"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = "kosugitti"
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "kosugitti"
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "kosugitti"
    slideshare      = "kosugitti"
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "kosugitti"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
