## Basic Configuration
baseurl = "https://kosugitti.github.io/kosugitti10/"
languageCode = "jp"
publishDir = "docs"
hasCJKLanguage = true
theme = "hyde-hyde"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Kosugitti"
    title = "Kosugitti Labo 10"
    description = "ようこそコスギコウジのオンライン研究室へ"
    authorimage = "/img/omodakatome.png"
    dateformat = "April 3, 2018"
    highlightjs = true
    # highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "kosugitti"
    instagram = "kosugitti"
    linkedin = "kosugitti"
    twitter = "kosugitti"
    email = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Profile"
    weight = 100
    identifier = "Profile"
    url = "/profile/"
[[menu.main]]
    name = "Works"
    weight = 100
    identifier = "Works"
    url = "/works/"
[[menu.main]]
    name = "Notes"
    weight = 100
    identifier = "Notes"
    url = "/notes/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
