---
title: "Support"
date: "2018-04-08T10:50:20+09:00"
---

## はじめに
このページでは，拙著の誤字脱字等，修正情報を広報いたします。

編集に際しては，何度も丁寧に校正しているつもりではありますが，どうしても完璧なものができませんで，ご迷惑をおかけしておりますことをお詫びいたします。



## 近刊のお知らせ

[Rでらくらく心理統計 RStudio徹底活用](https://amzn.to/2FVsfgz)

通称「言数ブラック」； [言葉と数式で理解する多変量解析入門](https://amzn.to/2L7qKf5)

通称「緑の紐本」； [研究論文を読み解くための多変量解析入門 基礎篇: 重回帰分析からメタ分析まで](https://amzn.to/2HuFD9s)

通称「青の紐本」； [研究論文を読み解くための多変量解析入門 応用篇: SEMから生存分析まで](https://amzn.to/2qru235)


## 訂正一覧

### 言葉と数式で理解する多変量解析入門

+ P.69 引用文献に脱字

  + 誤) 南風原朝和(2002) 理統計学の基礎
  + 正) 南風原朝和(2002) 心理統計学の基礎

### 豊田秀樹（編）「たのしいベイズモデリング」P.68--78 第7章，心の旅が始まる--観光のイメージの世代間比較--

+ P.68 7.1 個人差多次元尺度構成法 2行目
  + 誤) もちろんすべて言葉で表説明できるものでもない
  + 正) もちろん全て言葉で説明できるものでもない

+ P.70 L.15 
  + 誤) 一方，Bは左右方向を縮小し($w_{B2}<1$)，上下方向を拡大している($w_{B1}>1$)
  + 正) 一方，Bは左右方向を縮小し($w_{B1}<1$)，上下方向を拡大している($w_{B2}>1$)

+ P.73 表7.2 グループごとの回答者数
  + MとFのラベルが逆

+ P.73 L.3
  + 誤) 男性をF，女性をMと記号化している。20Fは20代男性，30Mは30大女性を意味する。
  + 正) 男性をM，女性をFと記号化している。20Mは20代男性，30Fは30大女性を意味する。

+ P.75 表7.3 回答群ごとの次元の重み
  + MとFのラベルが逆



### ソシオン理論入門―心と社会の基礎科学

[ソシオン理論入門―心と社会の基礎科学](https://amzn.to/2qseZqF)は2006年4月，北大路書房より出版されました。

##### P.1 　ジェイムズ「心理学」より

+ 誤）人が持っているもっとも特異な社会的自我は，彼が愛する物の心の中にあるものである。
+ 正）人が持っているもっとも特異な社会的自我は，彼が愛する<strong>者</strong>の心の中にあるものである。

### 社会調査士のための多変量解析法

[社会調査士のための多変量解析法](https://amzn.to/2HmpN39)は2007年5月，北大路書房より出版されました。

+ P.87 式[9.15]　共通性$h^2$の領域が$d_j^2$まで含んでいるが，正しくは$a_{jm}^2$まで。
+ P.104 平均値ベクトル$m$ の式中，$x'$は，正しくは$X'$.
+ P.109 図11.4で第一固有値の伸縮方向が(1,-2)になっているが，正しくは(1,1)方向。
+ P.125 T技法とS技法の説明が逆になっています。回答者間相関から(回答者)因子を出すのがS技法，時点間相関から(時間)因子を出すのがT技法


## M-plusとRによる構造方程式モデリング入門

[M-plusとRによる構造方程式モデリング入門](https://amzn.to/2HvoDQx)は2014年1月に北大路書房より出版されました。

この本につきましては，[専用のサポートサイト](https://sites.google.com/site/mplusandr/) にて対応します。

