---
title: "About"
date: "2018-04-08T10:50:20+09:00"
---

# ようこそコスギコウジのオンライン研究室へ

## 基本情報

+ 氏名　小杉考司 KOSUGI，Koji
+ 所属・職名　専修大学人間科学部 教授
+ 学位・資格　博士（社会学），専門社会調査士
+ 研究テーマ　数理社会心理学，統計モデリング
+ ORCID : https://orcid.org/0000-0001-5816-0099
+ Researchmap : https://researchmap.jp/kosugitti/


# 略歴

## 所属学会

+ 行動計量学会
+ 日本心理学会
+ 日本社会心理学会
+ 数理社会学会
+ 中国四国心理学会
+ 九州心理学会

## 略歴

+ 1976.01.17 大阪府大阪市生まれ
+ 1994.04　関西大学社会学部産業心理学専攻　入学
+ 1998.03　同　卒業
+ 1998.04　関西学院大学社会学研究科博士前期課程　入学
+ 2000.03　同　修了
+ 2000.04　同　後期課程　入学
+ 2003.03　同　単位取得退学
+ 2003.04～2004.5　関西学院大学大学院研究員（社会学研究科）として在籍
+ 2004.05～2005.3　関西学院大学研究科研究員（社会学研究科）として在籍
+ 2005.04～2007.3　日本学術振興会特別研究員PDとして関西学院大学（社会学研究科）に在籍
+ 2007.04～　山口大学教育学部に講師として奉職
+ 2011.04～　山口大学教育学部　准教授
+ 2018.04〜　専修大学人間科学部に准教授として
+ 2019.04より　現職

## 職歴

+ 2001.2002年度　星ヶ丘厚生年金保健看護専門学校にて「一般システム論」「疫学統計III」担当
+ 2001.2002年度　関西学院大学社会学部にて「コンピュータ基礎演習」担当
+ 2002.2003年度　夙川女子短期大学にて「社会心理学」担当
+ 2002～2004年度 神戸松蔭女子学院短期大学にて「人間関係論」担当
+ 2003～2004年度　神戸松蔭女子学院短期大学にて「心理学I/II」「社会心理学」担当
+ 2003～2004年度　大阪国際大学にて「集団コミュニケーションI/II」「心理学研究法I/II」「心理学実験実習I/II」担当
+ 2004年度　大阪国際大学にて「データ解析演習」担当
+ 2003～2006年度　関西学院大学社会学部にて「心理学実験A/B」担当
+ 2005～2006年度　関西学院大学社会学部にて「多変量解析法」担当
+ 2007年〜2018年度　山口大学教育学部教育心理学コースにて，「心理学統計法」「社会心理学」他，担当
+ 2018年度〜至現在 専修大学人間科学部にて「心理学データ解析基礎」 他担当
