---
title: "Notes"
date: "`r format(Sys.time(), '%Y/%m/%d')`"
---

# 日本心理学会「執筆・投稿の手引き」に準拠したBibtexのスタイルファイル

+ [心理学用bibtexスタイルファイル](https://github.com/kosugitti/jecon-jpa)(2018.10.21 update!)

# 心理統計の授業で使ったプロットのコード

+ [正規分布のコード](/2018/06/26/2018-06-26a/)
+ [標準正規分布のコード](/2018/06/30/2018-06-30/)
+ [正規分布の一部を塗りつぶす](/2018/06/29/2018-06-29b/)
+ [散布図のコード](/2018/06/26/2018-06-26c/)
+ [共分散を説明するときの図のコード](/2018/06/26/2018-06-26d/)
+ [標本平均の平均が母平均に一致する説明に使う図版](/2018/06/29/2018-06-29a/)
+ [不偏分散と標本分散の比較](/2018/07/04/2018-07-04/)
+ [t分布の図](/2018/07/06/t/)
+ [三つの代表値がずれる](/2018/07/06/mmm/)

# 過去の研究ノート(PDF)

+ [エルミート行列の固有値分解アルゴリズム](QR.pdf)
+ [正方行列の固有値分解--コスブラックP.167式9.2の補遺](Reigen.pdf)
+ [順序尺度の相関係数(ポリコリック相関係数)について](polychoricNote.pdf)
+ [確率分布についてのノート](prob.pdf)
+ [テキストデータを扱う多変量解析について](textMV.pdf)
+ [なぜ不偏分散はN-1で割るのかについて](whyN_1.pdf)
+ [双対尺度法についてのノート](DS2019.pdf)

# Macの環境に入れるべきものリスト(自分用メモ)

### HomebrewとHomebrewでいれるもの
+ Homebrew
+ iTerms2
+ RictyフォントとJapanesque配色
+ Dropbox
+ Atom
+ Typora
+ Calibre
+ Zotero
+ pyenv/anaconda
+ Docker
+ Chrome

### Homebrewを使わずに入れるべきもの1
+ MacTeX
+ R
+ RStudio
  + rstan/tidyverse
+ Tweetbot
+ mi
  + textools for mi
+ Parallels
