---
title: 標準正規分布の描画
author: ''
date: '2018-06-26'
slug: ''
categories:
  - note
tags:
  - R
banner: ''
description: ''
images: []
menu: ''
---

標準正規分布の描画 ；領域ごとの塗り分けを添えて

<!--more-->

```{r}

# パッケージの準備
library(ggplot2)
library(gridExtra)

# 関数の準備
limitRange <- function(fun, min, max) {
  function(x) {
    y <- fun(x)
    y[x < min  |  x > max] <- NA
    return(y)
  }
}
p <- ggplot(data.frame(x=c(-4, 4)), aes(x=x))
p + stat_function(fun = dnorm) +
  stat_function(fun = limitRange(dnorm, -1, 1),
                geom="area", fill="blue", alpha=0.2)+
  stat_function(fun = limitRange(dnorm, -2, 2),
                geom="area", fill="blue", alpha=0.2)+
  stat_function(fun = limitRange(dnorm, -3, 3),
                geom="area", fill="blue", alpha=0.2)
```

```{r}
# p(x>2)
p <- ggplot(data.frame(x=c(-4, 4)), aes(x=x))
p + stat_function(fun = dnorm) +
  stat_function(fun = limitRange(dnorm, 2, 4),
                geom="area", fill="blue", alpha=0.2)
```

```{r}
# 95%
p <- ggplot(data.frame(x=c(-4, 4)), aes(x=x))
p + stat_function(fun = dnorm) +
  stat_function(fun = limitRange(dnorm, -1.96, 1.96),
                geom="area", fill="blue", alpha=0.2)
```